### PR TITLE
introduce superlinter

### PR DESCRIPTION
**Pull request by klaernie**
This is only the bare bones config for now, I guess using #145 for the already fixed lint issues and and `.eslintrc` might still be a good idea

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
Nice.

All our other YAML files are with the file extention `.yml`. So I propose to rename `superlinter.yaml`.

**Comment by klaernie** [comment]
> All our other YAML files are with the file extention `.yml`. So I propose to rename `superlinter.yaml`.

I've always used `.yaml`, but people before me thought differently. So I now took a look at the world around to find some guidance what would be preferable, and the official faq has something reassuring in stock: https://yaml.org/faq.html
So maybe we should rename all the .yml files ;)

**Comment by KristjanESPERANTO** [comment]
> So maybe we should rename all the .yml files ;)

That was news to me. I think it makes sense to follow the official recommendation, so I created PR #150.

**Comment by KristjanESPERANTO** [comment]
You've been very busy :+1:

**Comment by klaernie** [comment]
> You've been very busy +1

Yeah, maybe a bit ;)

**Comment by klaernie** [comment]
@KristjanESPERANTO  do you have any idea how to fix this lint error? I'm not even sure I understand the line it complains about.
```
/home/runner/work/MMM-CalendarExt2/MMM-CalendarExt2/node_helper.js
Error:     5:41  error  'fetch' is already declared in the upper scope on line 4 column 7      no-shadow
```

**Comment by KristjanESPERANTO** [comment]
> do you have any idea how to fix this lint error? I'm not even sure I understand the line it complains about.

I don't understand it completely, but the reason is that `node-fetch` is an ESM-only module since v3 [[1]](https://www.npmjs.com/package/node-fetch#CommonJS) and we use this unusual import function for it.

I suggest that we disable the no-shadow rule for this one line. In the coming nodejs version there should be a built-in fetch function [[2]](https://github.com/MichMich/MagicMirror/issues/2649#issuecomment-1025466211), then we could say goodbye to node-fetch.

That could work:
```js
const fetch = (...args) =>
  // eslint-disable-next-line no-shadow
  import ("node-fetch").then(({ default: fetch }) => fetch(...args));
```

**Comment by KristjanESPERANTO** [comment]
As far as I can see, there are a few harder nuts left now. Just an idea: What do you say about merging this PR and handling the rest in new PRs? I am curious whether we have already broken something with the changes we have made so far 😅

**Comment by klaernie** [comment]
> Just an idea: What do you say about merging this PR and handling the rest in new PRs?
I had the same idea - so I'd say we go for it

> I am curious whether we have already broken something with the changes we have made so far 😅
Turns out you actually fixed something that has been broken for ages: The font was never applied, and substituted by `sans-serif`, since the necessary `@import` was misplaced.

I've run this branch in production for the last week, and haven't noticed anything breaking. So I'd guess since I'm the principal author of this branch, feel free to press the merge button!

**Comment by KristjanESPERANTO** [comment]
> Turns out you actually fixed something that has been broken for ages

Nice 🙂 So it has already paid off to introduce Linting 🎉 

> feel free to press the merge button!

I do not have a merge button. I guess I don't have the rights for it.

**Comment by klaernie** [comment]
> I do not have a merge button. I guess I don't have the rights for it.

Ouch... that was totally my fault. Fixed the permissions now, so now you can do what I intended the entire time.

**Pull request merged**
