### PR TITLE
Switch to monthly interval

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
Monthly should be more than enough.

### CODE REVIEW

**Comment by klaernie** [comment]
Good point. Maybe even superlinter upgrades in time for us..

**Comment by KristjanESPERANTO** [comment]
Thank you for your feedback! :slightly_smiling_face: 

Is it ok if I accept such minor changes right away or should I wait a bit so you have a chance to view it?

**Comment by klaernie** [comment]
They way you do is perfect! How work is done is always defined by the ones doing the work, so you have all the right to do as you like.

**Comment by KristjanESPERANTO** [comment]
I like that :slightly_smiling_face: We can also undo changes if necessary.

**Comment by klaernie** [comment]
Indeed, we have the power of git! ;)

**Pull request merged**
