### PR TITLE
Rework ESLint process

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
- Update dependencies
- Upgrade ESLint version
- Switch to flat config
- Replace airbnb config by stylistic
- Handle linter issues

### CODE REVIEW

**Comment by klaernie** [comment]
sorry for the noise - seems superlinter is not my favourite tool anymore, for keeping an old eslint that long..

**Comment by KristjanESPERANTO** [comment]
It looks good to me! Thanks :slightly_smiling_face:

**Comment by klaernie** [comment]
now superlinter only reports issues in CSS and JSON - and both errors do not really make sense to me, I'm clearly missing some information to understand it. Do you have better luck at grasping what is complains about?

**Comment by klaernie** [comment]
I think the main annoyance comes (at least for me) from its older tooling for JavaScript and CSS. If we now we're to disable CSS and json linting, it would still give good advice for natural language and GitHub actions, and would be quite nice to have when I finally get to improving the documentation.
Else we could still have a look at mega-linter, which does a similar job, but I have not looked deeply into that one yet.

**Comment by KristjanESPERANTO** [comment]
I was free to take the step for a point release. Hope that's okay :slightly_smiling_face:

**Comment by klaernie** [comment]
> I was free to take the step for a point release. Hope that's okay 🙂

Always! Thanks!

**Pull request merged**
