### PR TITLE
Add linter and prettier

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
A proposal to introduce linters. That's quite a lot of changes, but I don't rate any of them as critical.

There are still many linter issues open, but I wanted to see if the direction is OK. We can of course set other linter rules. I have taken the linter rules from my other modules ([MMM-PublicTransportHafas](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas)).

### CODE REVIEW

**Comment by klaernie** [comment]
Having linters makes most definitely sense! Thanks for the suggestion!

I've run a lot with superlinter in the past - which would do eslint, but also lint the documentation and everything else it can turn up. What are your thoughts about that?

**Comment by KristjanESPERANTO** [comment]
Are you talking about this one: https://github.com/github/super-linter? That looks very interesting :smiley: I didn't know it yet. And I also see the advantage that it supports many more formats.

We can drop the Eslint approach and give Super-Lint a chance.

**Comment by klaernie** [comment]
Cool. That's the config I've used before: https://github.com/klaernie/docker-MagicMirror/blob/main/.github/workflows/superlinter.yaml

**Comment by KristjanESPERANTO** [comment]
I'll take a look at it. But I can't promise to do a PR soon. If someone is faster, I won't be sad about it ;-)

I suggest to leave this PR open until there is a new one for Super-Linter.

**Comment by klaernie** [comment]
After a bit of thought, I'd go the way of merging this, then removing the workflow declaration afterwards. This way we have all the already fixed linting issues as a base for the superlinter branch, and can also compare what the "bare" eslint reports

**Pull request merged**
