### PR TITLE
Maintenance update

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
- Update dependencies
- Update ESLint env
- Replace eslint-plugin-json by eslint-plugin-jsonc
- Update URLs to MagicMirror project

### CODE REVIEW

**Comment by klaernie** [comment]
Thanks @KristjanESPERANTO !

**Comment by KristjanESPERANTO** [comment]
Your welcome :slightly_smiling_face: 

Off topic: Did you already saw my [new project](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/)?

**Comment by klaernie** [comment]
Nice work! Looks really neat, and definitely deserves time in the spotlight.

**Comment by KristjanESPERANTO** [comment]
Thank you for the kudos and your suggestions! Let's see how it evolves :smiley:

**Pull request merged**
